name: flutterapp
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  # Device Info
  device_info: ^0.4.2+1
  # Shared preferences support save local data
  shared_preferences: ^0.5.6+3
  # SQFlite support save local database - SQL
  sqflite: ^1.3.0
  # RxDart
  rxdart: ^0.23.1
  # A Flutter plugin for launching a URL in the mobile platform.
  url_launcher: ^5.4.2
  # A Flutter plugin to share content from your Flutter app via the platform's share dialog.
  share: ^0.6.3+6
  # A Flutter plugin for iOS and Android for picking images from the image library, and taking new pictures with the camera.
  image_picker: ^0.6.3+4
  # A Flutter plugin that provides a WebView widget.
  webview_flutter: ^0.3.19+9
  # A powerful Http client for Dart, which supports Interceptors, Global configuration,
  # FormData, Request Cancellation, File downloading, Timeout etc.
  dio: ^3.0.9
  # A permissions plugin for Flutter. This plugin provides a cross-platform (iOS, Android) API to request and check permissions.
  permission_handler: ^4.4.0+hotfix.2
  # Cached network image
  cached_network_image: ^2.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Setup link assets image or public/private key
  assets:
    - assets/
    - assets/images/

  # Setup link font folder
  # fonts:
  #  - family: SFUIText
  #    fonts:
  #      - asset: assets/fonts/SFUIText-Regular.ttf
